/* Generated by wayland-scanner 1.25.0 */

#ifndef ANDROID_WLEGL_SERVER_PROTOCOL_H
#define ANDROID_WLEGL_SERVER_PROTOCOL_H

#include <stdint.h>
#include <stddef.h>
#include "wayland-server.h"

#ifdef  __cplusplus
extern "C" {
#endif

struct wl_client;
struct wl_resource;

/**
 * @page page_android_wlegl The android_wlegl protocol
 * @section page_ifaces_android_wlegl Interfaces
 * - @subpage page_iface_android_wlegl - Android EGL graphics buffer support
 * - @subpage page_iface_android_wlegl_handle - 
 * @section page_copyright_android_wlegl Copyright
 * <pre>
 *
 * Copyright © 2012 Collabora, Ltd.
 *
 * Permission to use, copy, modify, distribute, and sell this
 * software and its documentation for any purpose is hereby granted
 * without fee, provided that the above copyright notice appear in
 * all copies and that both that copyright notice and this permission
 * notice appear in supporting documentation, and that the name of
 * the copyright holders not be used in advertising or publicity
 * pertaining to distribution of the software without specific,
 * written prior permission. The copyright holders make no
 * representations about the suitability of this software for any
 * purpose. It is provided "as is" without express or implied
 * warranty.
 * </pre>
 */
struct android_wlegl;
struct android_wlegl_handle;
struct wl_buffer;

#ifndef ANDROID_WLEGL_INTERFACE
#define ANDROID_WLEGL_INTERFACE
/**
 * @page page_iface_android_wlegl android_wlegl
 * @section page_iface_android_wlegl_desc Description
 *
 * Interface used in Android EGL wrapper libEGL to share graphics buffers
 * between the server and the client.
 * @section page_iface_android_wlegl_api API
 * See @ref iface_android_wlegl.
 */
/**
 * @defgroup iface_android_wlegl The android_wlegl interface
 *
 * Interface used in Android EGL wrapper libEGL to share graphics buffers
 * between the server and the client.
 */
extern const struct wl_interface android_wlegl_interface;
#endif
#ifndef ANDROID_WLEGL_HANDLE_INTERFACE
#define ANDROID_WLEGL_HANDLE_INTERFACE
/**
 * @page page_iface_android_wlegl_handle android_wlegl_handle
 * @section page_iface_android_wlegl_handle_api API
 * See @ref iface_android_wlegl_handle.
 */
/**
 * @defgroup iface_android_wlegl_handle The android_wlegl_handle interface
 */
extern const struct wl_interface android_wlegl_handle_interface;
#endif

#ifndef ANDROID_WLEGL_ERROR_ENUM
#define ANDROID_WLEGL_ERROR_ENUM
enum android_wlegl_error {
	ANDROID_WLEGL_ERROR_BAD_HANDLE = 0,
	ANDROID_WLEGL_ERROR_BAD_VALUE = 1,
};
#endif /* ANDROID_WLEGL_ERROR_ENUM */

#ifndef ANDROID_WLEGL_ERROR_ENUM_IS_VALID
#define ANDROID_WLEGL_ERROR_ENUM_IS_VALID
/**
 * @ingroup iface_android_wlegl
 * Validate a android_wlegl error value.
 *
 * @return true on success, false on error.
 * @ref android_wlegl_error
 */
static inline bool
android_wlegl_error_is_valid(uint32_t value, uint32_t version) {
	switch (value) {
	case ANDROID_WLEGL_ERROR_BAD_HANDLE:
		return version >= 1;
	case ANDROID_WLEGL_ERROR_BAD_VALUE:
		return version >= 1;
	default:
		return false;
	}
}
#endif /* ANDROID_WLEGL_ERROR_ENUM_IS_VALID */

/**
 * @ingroup iface_android_wlegl
 * @struct android_wlegl_interface
 */
struct android_wlegl_interface {
	/**
	 */
	void (*create_handle)(struct wl_client *client,
			      struct wl_resource *resource,
			      uint32_t id,
			      int32_t num_fds,
			      struct wl_array *ints);
	/**
	 */
	void (*create_buffer)(struct wl_client *client,
			      struct wl_resource *resource,
			      uint32_t id,
			      int32_t width,
			      int32_t height,
			      int32_t stride,
			      int32_t format,
			      int32_t usage,
			      struct wl_resource *native_handle);
};

#define ANDROID_WLEGL_FORMAT 0

/**
 * @ingroup iface_android_wlegl
 */
#define ANDROID_WLEGL_FORMAT_SINCE_VERSION 1

/**
 * @ingroup iface_android_wlegl
 */
#define ANDROID_WLEGL_CREATE_HANDLE_SINCE_VERSION 1
/**
 * @ingroup iface_android_wlegl
 */
#define ANDROID_WLEGL_CREATE_BUFFER_SINCE_VERSION 1

/**
 * @ingroup iface_android_wlegl
 * Sends an format event to the client owning the resource.
 * @param resource_ The client's resource
 */
static inline void
android_wlegl_send_format(struct wl_resource *resource_, uint32_t format)
{
	wl_resource_post_event(resource_, ANDROID_WLEGL_FORMAT, format);
}

#ifndef ANDROID_WLEGL_HANDLE_ERROR_ENUM
#define ANDROID_WLEGL_HANDLE_ERROR_ENUM
enum android_wlegl_handle_error {
	ANDROID_WLEGL_HANDLE_ERROR_TOO_MANY_FDS = 0,
};
#endif /* ANDROID_WLEGL_HANDLE_ERROR_ENUM */

#ifndef ANDROID_WLEGL_HANDLE_ERROR_ENUM_IS_VALID
#define ANDROID_WLEGL_HANDLE_ERROR_ENUM_IS_VALID
/**
 * @ingroup iface_android_wlegl_handle
 * Validate a android_wlegl_handle error value.
 *
 * @return true on success, false on error.
 * @ref android_wlegl_handle_error
 */
static inline bool
android_wlegl_handle_error_is_valid(uint32_t value, uint32_t version) {
	switch (value) {
	case ANDROID_WLEGL_HANDLE_ERROR_TOO_MANY_FDS:
		return version >= 1;
	default:
		return false;
	}
}
#endif /* ANDROID_WLEGL_HANDLE_ERROR_ENUM_IS_VALID */

/**
 * @ingroup iface_android_wlegl_handle
 * @struct android_wlegl_handle_interface
 */
struct android_wlegl_handle_interface {
	/**
	 */
	void (*add_fd)(struct wl_client *client,
		       struct wl_resource *resource,
		       int32_t fd);
	/**
	 */
	void (*destroy)(struct wl_client *client,
			struct wl_resource *resource);
};


/**
 * @ingroup iface_android_wlegl_handle
 */
#define ANDROID_WLEGL_HANDLE_ADD_FD_SINCE_VERSION 1
/**
 * @ingroup iface_android_wlegl_handle
 */
#define ANDROID_WLEGL_HANDLE_DESTROY_SINCE_VERSION 1

#ifdef  __cplusplus
}
#endif

#endif
