/* Generated by wayland-scanner 1.25.0 */

/*
 * Copyright © 2012 Collabora, Ltd.
 *
 * Permission to use, copy, modify, distribute, and sell this
 * software and its documentation for any purpose is hereby granted
 * without fee, provided that the above copyright notice appear in
 * all copies and that both that copyright notice and this permission
 * notice appear in supporting documentation, and that the name of
 * the copyright holders not be used in advertising or publicity
 * pertaining to distribution of the software without specific,
 * written prior permission. The copyright holders make no
 * representations about the suitability of this software for any
 * purpose. It is provided "as is" without express or implied
 * warranty.
 */

#include <stdbool.h>
#include <stdlib.h>
#include <stdint.h>
#include "wayland-util.h"

#ifndef __has_attribute
# define __has_attribute(x) 0  /* Compatibility with non-clang compilers. */
#endif

#if (__has_attribute(visibility) || defined(__GNUC__) && __GNUC__ >= 4)
#define WL_PRIVATE __attribute__ ((visibility("hidden")))
#else
#define WL_PRIVATE
#endif

extern const struct wl_interface android_wlegl_handle_interface;
extern const struct wl_interface wl_buffer_interface;

static const struct wl_interface *android_wlegl_types[] = {
	NULL,
	&android_wlegl_handle_interface,
	NULL,
	NULL,
	&wl_buffer_interface,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	&android_wlegl_handle_interface,
};

static const struct wl_message android_wlegl_requests[] = {
	{ "create_handle", "nia", android_wlegl_types + 1 },
	{ "create_buffer", "niiiiio", android_wlegl_types + 4 },
};

static const struct wl_message android_wlegl_events[] = {
	{ "format", "u", android_wlegl_types + 0 },
};

WL_PRIVATE const struct wl_interface android_wlegl_interface = {
	"android_wlegl", 1,
	2, android_wlegl_requests,
	1, android_wlegl_events,
};

static const struct wl_message android_wlegl_handle_requests[] = {
	{ "add_fd", "h", android_wlegl_types + 0 },
	{ "destroy", "", android_wlegl_types + 0 },
};

WL_PRIVATE const struct wl_interface android_wlegl_handle_interface = {
	"android_wlegl_handle", 1,
	2, android_wlegl_handle_requests,
	0, NULL,
};

